Controllers/DangkiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BTL_PTPMQL_NHOM12.Models;
using BTL_PTPMQL_NHOM12.Models.Process;

namespace BTL_PTPMQL_NHOM12.Controllers
{
    public class DangkiController : Controller
    {
        private readonly ApplicationDbContext _context;
        private StringProcess Ngid = new StringProcess();

        public DangkiController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Dangki
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Dangki.Include(d => d.Dichvu).Include(d => d.Khachhang);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Dangki/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Dangki == null)
            {
                return NotFound();
            }

            var dangki = await _context.Dangki
                .Include(d => d.Dichvu)
                .Include(d => d.Khachhang)
                .FirstOrDefaultAsync(m => m.MaDK == id);
            if (dangki == null)
            {
                return NotFound();
            }

            return View(dangki);
        }

        // GET: Dangki/Create
        public IActionResult Create()
        {
            //sinh mã tự động
            var newIDn ="MA0112";
            var countNTN  =_context.Dangki.Count();
            if(countNTN >0 )
            {
                var MaDK=_context.Dangki.OrderByDescending(m=>m.MaDK).First().MaDK;
                newIDn = Ngid.AutoGenerateCode(MaDK);
            }
            ViewBag.newID= newIDn;
            //Khóa ngoại
            ViewData["MaDV"] = new SelectList(_context.Dichvu, "MaDV", "MaDV");
            ViewData["MaKH"] = new SelectList(_context.Khachhang, "MaKH", "MaKH");
            return View();
        }

        // POST: Dangki/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaDK,MaKH,MaDV,NgayDangKi,SoLuong")] Dangki dangki)
        {
            if (ModelState.IsValid)
            {
                _context.Add(dangki);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaDV"] = new SelectList(_context.Dichvu, "MaDV", "MaDV", dangki.MaDV);
            ViewData["MaKH"] = new SelectList(_context.Khachhang, "MaKH", "MaKH", dangki.MaKH);
            return View(dangki);
        }

        // GET: Dangki/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Dangki == null)
            {
                return NotFound();
            }

            var dangki = await _context.Dangki.FindAsync(id);
            if (dangki == null)
            {
                return NotFound();
            }
            ViewData["MaDV"] = new SelectList(_context.Dichvu, "MaDV", "MaDV", dangki.MaDV);
            ViewData["MaKH"] = new SelectList(_context.Khachhang, "MaKH", "MaKH", dangki.MaKH);
            return View(dangki);
        }

        // POST: Dangki/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("MaDK,MaKH,MaDV,NgayDangKi,SoLuong")] Dangki dangki)
        {
            if (id != dangki.MaDK)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(dangki);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DangkiExists(dangki.MaDK))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaDV"] = new SelectList(_context.Dichvu, "MaDV", "MaDV", dangki.MaDV);
            ViewData["MaKH"] = new SelectList(_context.Khachhang, "MaKH", "MaKH", dangki.MaKH);
            return View(dangki);
        }

        // GET: Dangki/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.Dangki == null)
            {
                return NotFound();
            }

            var dangki = await _context.Dangki
                .Include(d => d.Dichvu)
                .Include(d => d.Khachhang)
                .FirstOrDefaultAsync(m => m.MaDK == id);
            if (dangki == null)
            {
                return NotFound();
            }

            return View(dangki);
        }

        // POST: Dangki/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.Dangki == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Dangki'  is null.");
            }
            var dangki = await _context.Dangki.FindAsync(id);
            if (dangki != null)
            {
                _context.Dangki.Remove(dangki);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DangkiExists(string id)
        {
          return (_context.Dangki?.Any(e => e.MaDK == id)).GetValueOrDefault();
        }
    }
}

Controllers/DichvuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BTL_PTPMQL_NHOM12.Models;
using BTL_PTPMQL_NHOM12.Models.Process;
namespace BTL_PTPMQL_NHOM12.Controllers
{
    public class DichvuController : Controller
    {
        private readonly ApplicationDbContext _context;
        private StringProcess Ngid = new StringProcess();

        public DichvuController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Dichvu
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Dichvu.Include(d => d.Loaidichvu);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Dichvu/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Dichvu == null)
            {
                return NotFound();
            }

            var dichvu = await _context.Dichvu
                .Include(d => d.Loaidichvu)
                .FirstOrDefaultAsync(m => m.MaDV == id);
            if (dichvu == null)
            {
                return NotFound();
            }

            return View(dichvu);
        }

        // GET: Dichvu/Create
        public IActionResult Create()
        {
             //sinh mã tự động
            var newIDn ="DV021";
            var countNTN  =_context.Dichvu.Count();
            if(countNTN >0 )
            {
                var MaDV=_context.Dichvu.OrderByDescending(m=>m.MaDV).First().MaDV;
                newIDn = Ngid.AutoGenerateCode(MaDV);
            }
            ViewBag.newID= newIDn;
            //Khóa ngoại
            ViewData["MaLoaiDV"] = new SelectList(_context.Loaidichvu, "MaLoaiDV", "MaLoaiDV");
            return View();
        }

        // POST: Dichvu/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaDV,MaLoaiDV,TenDV,DonViTinh,DonGia,GhiChu")] Dichvu dichvu)
        {
            if (ModelState.IsValid)
            {
                _context.Add(dichvu);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaLoaiDV"] = new SelectList(_context.Loaidichvu, "MaLoaiDV", "MaLoaiDV", dichvu.MaLoaiDV);
            return View(dichvu);
        }

        // GET: Dichvu/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Dichvu == null)
            {
                return NotFound();
            }

            var dichvu = await _context.Dichvu.FindAsync(id);
            if (dichvu == null)
            {
                return NotFound();
            }
            ViewData["MaLoaiDV"] = new SelectList(_context.Loaidichvu, "MaLoaiDV", "MaLoaiDV", dichvu.MaLoaiDV);
            return View(dichvu);
        }

        // POST: Dichvu/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("MaDV,MaLoaiDV,TenDV,DonViTinh,DonGia,GhiChu")] Dichvu dichvu)
        {
            if (id != dichvu.MaDV)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(dichvu);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DichvuExists(dichvu.MaDV))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaLoaiDV"] = new SelectList(_context.Loaidichvu, "MaLoaiDV", "MaLoaiDV", dichvu.MaLoaiDV);
            return View(dichvu);
        }

        // GET: Dichvu/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.Dichvu == null)
            {
                return NotFound();
            }

            var dichvu = await _context.Dichvu
                .Include(d => d.Loaidichvu)
                .FirstOrDefaultAsync(m => m.MaDV == id);
            if (dichvu == null)
            {
                return NotFound();
            }

            return View(dichvu);
        }

        // POST: Dichvu/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.Dichvu == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Dichvu'  is null.");
            }
            var dichvu = await _context.Dichvu.FindAsync(id);
            if (dichvu != null)
            {
                _context.Dichvu.Remove(dichvu);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DichvuExists(string id)
        {
          return (_context.Dichvu?.Any(e => e.MaDV == id)).GetValueOrDefault();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] -HỆ THỐNG GN</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BTL_PTPMQL_NHOM12.styles.css" asp-append-version="true" />
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css'
        integrity='sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=='
        crossorigin='anonymous' />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand nhom12" asp-area="" asp-controller="Home" asp-action="Index">PTPMQL-NHOM12 </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @* @if (TempData["Login"] != null)
                { *@
                   
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between ">
                    <ul class="navbar-nav flex-grow-1">
                        @* <li class="nav-item">
                            <a class="nav-link text-dark " asp-area="" asp-controller="Home" asp-action="Index" >HOME </a>
                            </li> *@
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li> *@
                        <li class="nav-item">
                            <a class="nav-link text-dark btn-home " asp-area="" asp-controller="Nhanvien" asp-action="Index">Nhân viên </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark btn-home" asp-area="" asp-controller="Nguoiquanli"
                                asp-action="Index"> Người quản lí </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark btn-home" asp-area="" asp-controller="Khachhang"
                                asp-action="Index">Khách hàng </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark btn-home" asp-area="" asp-controller="Dichvu" asp-action="Index">Dịch vụ
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark btn-home" asp-area="" asp-controller="Kyhopdong" asp-action="Index">Kí hợp đồng </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark btn-home" asp-area="" asp-controller="Dangki" asp-action="Index">Đăng kí </a>
                        </li>
                        <li class="nav-item btn-home">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Giaonhan" asp-action="Index">Giao nhận</a>
                        </li>

                    </ul>
                </div>
                @* } *@

            </div>
        </nav>
        <div>
        </div>

    </header>
    <div class="container">
        <main role="main" class="pb-3 ">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted ">
        <div class="container">
            &copy; Tiếp nhận và quản lí dịch vụ cho khách hàng<a asp-area="" style="text-decoration: none"
                asp-controller="Home" asp-action="Index"> ........Trang chủ</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>
<style>
.btn-home:hover{
    border-bottom: solid 1px rgb(91, 107, 107);
    opacity: 0.6;
    }
.nhom12{
    font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;
}
</style>