Models/Phongban.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace  BTL_PTPMQL_NHOM12.Models
{
    public class Phongban
    {
        [Key]

        [Required(ErrorMessage ="Mã phòng ban không được để trống")]
        [Display(Name ="Mã phòng ban")]
        public string? MaPB {get; set;}

        [Required(ErrorMessage ="Tên phòng ban không được để trống")]
        [Display(Name ="Tên phòng ban")]
        public string? TenPB {get; set;}
    }
}

Controllers/PhongbanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BTL_PTPMQL_NHOM12.Models.Process;
using BTL_PTPMQL_NHOM12.Models;

namespace BTL_PTPMQL_NHOM12.Controllers
{
    public class PhongbanController : Controller
    {
        private readonly ApplicationDbContext _context;
        private ExcelProcess _excelProcess =new ExcelProcess();

        public PhongbanController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Phongban
        // public async Task<IActionResult> Index()
        // {
        //       return _context.Phongban != null ? 
        //                   View(await _context.Phongban.ToListAsync()) :
        //                   Problem("Entity set 'ApplicationDbContext.Phongban'  is null.");
        // }
          //Tìm kiếm
        public async Task<IActionResult> Index(string TimkiemPB, string searchString)
        {
            if (_context.Phongban == null)
            {
                return Problem("Entity set 'MvcMovieContext.Movie'  is null.");
            }

            // Use LINQ to get list of genres.
            IQueryable<string> genreQuery = from m in _context.Phongban
                                            orderby m.TenPB
                                            select m.TenPB;
            var Phongban = from m in _context.Phongban
                         select m;

            if (!string.IsNullOrEmpty(searchString))
            {
                Phongban = Phongban.Where(s => s.TenPB!.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(TimkiemPB))
            {
                Phongban = Phongban.Where(x => x.TenPB == TimkiemPB);
            }

            var movieGenreVM = new MovieGenreViewModel
            {
                TenPB = new SelectList(await genreQuery.Distinct().ToListAsync()),
                Phongban = await Phongban.ToListAsync()
            };

            return View(movieGenreVM);
        }
        ////Kết thúc tìm kiếm

        // GET: Phongban/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Phongban == null)
            {
                return NotFound();
            }

            var phongban = await _context.Phongban
                .FirstOrDefaultAsync(m => m.MaPB == id);
            if (phongban == null)
            {
                return NotFound();
            }

            return View(phongban);
        }

        // GET: Phongban/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Phongban/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaPB,TenPB")] Phongban phongban)
        {
            if (ModelState.IsValid)
            {
                _context.Add(phongban);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(phongban);
        }

        // GET: Phongban/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Phongban == null)
            {
                return NotFound();
            }

            var phongban = await _context.Phongban.FindAsync(id);
            if (phongban == null)
            {
                return NotFound();
            }
            return View(phongban);
        }

        // POST: Phongban/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("MaPB,TenPB")] Phongban phongban)
        {
            if (id != phongban.MaPB)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(phongban);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PhongbanExists(phongban.MaPB))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(phongban);
        }

        // GET: Phongban/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.Phongban == null)
            {
                return NotFound();
            }

            var phongban = await _context.Phongban
                .FirstOrDefaultAsync(m => m.MaPB == id);
            if (phongban == null)
            {
                return NotFound();
            }

            return View(phongban);
        }

        // POST: Phongban/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.Phongban == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Phongban'  is null.");
            }
            var phongban = await _context.Phongban.FindAsync(id);
            if (phongban != null)
            {
                _context.Phongban.Remove(phongban);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PhongbanExists(string id)
        {
          return (_context.Phongban?.Any(e => e.MaPB == id)).GetValueOrDefault();
        }
         ////Thêm upload
         public async Task<IActionResult> Upload()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upload(IFormFile file)
        {
            if(file!=null)
            {
                string fileExtension =Path.GetExtension(file.FileName);
                if (fileExtension != ".xls" && fileExtension != ".xlsx")
                {
                    ModelState.AddModelError("","Please choose excel file to upload!");
                }
                else{
                    var FileName = DateTime.Now.ToShortTimeString() + fileExtension;
                    var filePath = Path.Combine(Directory.GetCurrentDirectory() + "/Uploads/Excels", FileName);
                    var fileLocation = new FileInfo(filePath).ToString();
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        //save file to sever
                        await file.CopyToAsync(stream);
                        var dt = _excelProcess.ExcelToDataTable(fileLocation);
                        for (int i=0; i < dt.Rows.Count; i++)
                        {
                            var emp = new Phongban();

                            emp.MaPB=dt.Rows[i][0].ToString();
                            emp.TenPB=dt.Rows[i][1].ToString();
                            
                            _context.Phongban.Add(emp);
                        }
                        await _context.SaveChangesAsync();
                        return RedirectToAction(nameof(Index));
                    }
                }
            }
            return View();
    }
}
}

Views/Phongban/Create.cshtml
@model BTL_PTPMQL_NHOM12.Models.Phongban

@{
    ViewData["Title"] = "Create";
}

<h1>Tạo mới</h1>

<h4>Bảng phòng ban</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MaPB" class="control-label"></label>
                <input asp-for="MaPB" class="form-control" />
                <span asp-validation-for="MaPB" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TenPB" class="control-label"></label>
                <input asp-for="TenPB" class="form-control" />
                <span asp-validation-for="TenPB" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary btn-create" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="add_TSX">Trở lại danh sách</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Phongban/Delete.cshtml
@model BTL_PTPMQL_NHOM12.Models.Phongban

@{
    ViewData["Title"] = "Delete";
}

<h1>Bạn có muốn xóa</h1>

<h3>Bảng phòng ban</h3>
<div>
    @* <h4>Phongban</h4> *@
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TenPB)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TenPB)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="MaPB" />
        <input type="submit" value="Delete" class="btn btn-danger btn-delete" /> |
        <a asp-action="Index" class="add_TSX">Trở lại danh sách</a>
    </form>
</div>

Views/Phongban/Details.cshtml
@model BTL_PTPMQL_NHOM12.Models.Phongban

@{
    ViewData["Title"] = "Details";
}

<h1>Thông tin chi tiết</h1>

<div>
    <h4>Bảng phòng ban</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TenPB)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TenPB)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.MaPB" class="add_TSX">Edit</a> |
    <a asp-action="Index" class="add_TSX">Trở lại danh sách</a>
</div>

Views/Phongban/Edit.cshtml
@model BTL_PTPMQL_NHOM12.Models.Phongban

@{
    ViewData["Title"] = "Edit";
}

<h1>Chỉnh sửa</h1>

<h4>Bảng phòng ban</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MaPB" />
            <div class="form-group">
                <label asp-for="TenPB" class="control-label"></label>
                <input asp-for="TenPB" class="form-control" />
                <span asp-validation-for="TenPB" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="add_TSX">Trở lại danh sách</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Phongban/Index.cshtml
@* @model IEnumerable<BTL_PTPMQL_NHOM12.Models.Phongban> *@
@model BTL_PTPMQL_NHOM12.Models.MovieGenreViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>Bảng Phòng ban</h1>

<p>
    <a asp-action="Create" class="add-create">Thêm phòng ban</a> |
    <a asp-action="Upload" class="add-create">Tải lên</a>
    @* Tạo thanh tìm kiếm *@
    <form asp-controller="Phongban" asp-action="Index" method="get">
    <p>

        <select asp-for="TimkiemPB" asp-items="Model.TenPB" class="input">
            <option value="">Tất cả</option>
        </select>
        <input type="text" asp-for="SearchString"  placeholder="Tìm kiếm" class="input"/>
        <input type="submit" value="Tìm kiếm" class="submit"/>
    </p>
</form>
@* ////////////keet thuc tao tìm kiếm *@

</p>
<table class="table">
    <thead>
        <tr>
             @* <th>
                @Html.DisplayNameFor(model => model.MaPB)
            </th> *@
            <th>
                @Html.DisplayNameFor(model => model.TenPB)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Phongban) {
        <tr>
             <td>
                @Html.DisplayFor(modelItem => item.MaPB)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TenPB)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.MaPB" class="add_TSX">Sửa</a> |
                <a asp-action="Details" asp-route-id="@item.MaPB" class="add_TSX">Chi tiết</a> |
                <a asp-action="Delete" asp-route-id="@item.MaPB" class="add_TSX">Xóa</a> 
             
            </td>
        </tr>
}
    </tbody>
</table>

Views/Phongban/Upload.cshtml
@{
    ViewData["Title"] ="Upload";
}
<h1>Thêm dữ liệu  </h1>
<h4>@ViewBag.Dulieu</h4>
<hr/>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Upload" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div>
                <label>Thêm file Excel</label>
                <input name="file" type="file" class="form-control">
                <br>
            </div>
            <div class="form-group">
                <input type="submit" value="Upload" class="btn btn-primary">
                <a asp-action="Index" class="btn btn-info" class="add_TSX"> Trở lại danh sách</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}